[package]
name = "openapi_utils"
version = "0.1.1"
authors = ["Jordi Polo <mumismo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openapiv3 = "0.3.0"
log = "*"
indexmap = "1.3.0"
http = "*"
